#!/bin/sh

result="$(apropos . 2>/dev/null | dmenu -f -l 5 -p 'Open: ')"

[ -z "$result" ] && exit 0

page=$(printf "%s" "$result" | sed 's/^\([^ (]*\).*/\1/' | tr -d ',')
sect=$(printf "%s" "$result" | sed -n 's/.*(\([^)]*\)).*/\1/p' |
	cut -d',' -f1)

printf "%s %s\n" "$page" "$sect"

if [ -n "$page" ] && [ -n "$sect" ]; then
	alacritty -e man "$sect" "$page"
fi

